config:
  img_size: 56
  patch_size: 8
  embed_dim: 512
  depth: 12
  num_heads: 16
  decoder_embed_dim: 256
  decoder_depth: 4
  decoder_num_heads: 16
  mlp_ratio: 4
outdir: test
trainData: ../data/example/dense_2d_voxEdep_56x56_example.h5
testData: ../data/example/dense_2d_voxEdep_56x56_example_test.h5
batchSize: 128
maxEpoch: 1000
lr: 1.e-7
